apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-deployment
spec:
  selector:
    matchLabels:
       app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
      - name: aggregator
        image: rajsingh6/aggregatorservice:v10
        ports:
          - containerPort: 8070
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "dev"

---
apiVersion: v1
kind: Service
metadata:
    name: aggregator-service
spec:
    type: ClusterIP
    selector:
        app: aggregator
    ports:
    - port: 8070
      targetPort: 8070

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: aggregator-ingress
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        
spec:
   rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: aggregator-service
              servicePort: 8070